****

# 

### <center> <b> <span style="color:green;"> .</span> </b></center>


****

# <center> <b> <span style="color:blue;">Introduction à Numpy </span> </b></center>
<center> <b> <span style="color:orange;"> Par Andy DEGBEGNI </span> </b></center>


<!--NAVIGATION-->
< [Sommaire](Index.ipynb) | [1. Généralités] >



****

### <left> <b> <span style="color:brown;"> </span> </b></left>

Numpy (Numerical Python), est une bibliothèque composée d'objets de tableaux multidimensionnels et d'une collection de routines permettant de traiter ces tableaux. NumPy permet d'effectuer des opérations mathématiques et logiques sur des tableaux. Il est open source.
****



### Les opérations avec NumPy

À l'aide de NumPy, un développeur peut effectuer les opérations suivantes :

    1. Opérations mathématiques et logiques sur des tableaux.

    2. Transformations de Fourier et routines de manipulation de formes.

    3. Opérations liées à l'algèbre linéaire. NumPy possède des fonctions intégrées pour l'algèbre linéaire et la génération de nombres aléatoires

### NumPy - Un remplacement pour MatLab

NumPy est souvent utilisé avec des paquets comme SciPy (Python scientifique) et Mat-plotlib (bibliothèque de traçage). Cette combinaison est largement utilisée pour remplacer MatLab, une plate-forme populaire pour l'informatique technique. Cependant, l'alternative Python à MatLab est désormais considérée comme un langage de programmation plus moderne et plus complet.

### Numpy - Environement et Installation

La distribution standard de Python ne contient pas le module NumPy. Une alternative légère consiste à installer NumPy à l'aide du populaire installateur de paquets Python, pip.
La meilleure façon d'activer NumPy est d'utiliser un paquetage binaire installable spécifique à votre système d'exploitation. 

##### Windows
Pour les utilisateurs de Windows, les alternatives suivantes s'offrent à vous : <br/><br/>
    - Anaconda ( https://www.continuum.io) est une distribution gratuite de Python pour la pile SciPy. Elle est également disponible pour Linux et Mac.<br/>
    - Canopy (https://www.enthought.com/products/canopy/) est disponible en tant que distribution libre et commerciale avec la pile SciPy complète pour Windows, Linux et Mac.<br/>
    - Python (x,y) : Il s'agit d'une distribution gratuite de Python avec la pile SciPy et l'IDE Spyder pour Windows OS. (Téléchargeable sur https://www.python-xy.github.io/)

##### Linux 
Pour les utilisateurs linux : <br/><br/>

> **Pour Ubuntu:** <br/>
sudo apt-get install python-numpy <br/>
python-scipy python-matplotlibipythonipythonnotebook python-pandas <br/>
python-sympy python-nose <br/>

### Tester si le module a été bien installer 

Pour vérifier si le module NumPy est correctement installé, essayez de l'importer à partir de l'invite Python en faisant :

In [195]:
import numpy 
ou encore : 
import numpy as np

SyntaxError: invalid syntax (<ipython-input-195-fb770dd4ba45>, line 2)

S'il n'est pas installé, le message d'erreur suivant s'affiche.

Traceback (most recent call last): <br/>
   File "<pyshell#0>", line 1, in <module> <br/> 
      import numpy <br/>
ImportError: No module named 'numpy' <br/>

Sinon, aucun message ne sera affiché.

### NumPy - Ndarray Object

L'objet le plus important défini dans NumPy est un type de tableau à N dimensions appelé ndarray. Il décrit la collection d'éléments du même type. Les éléments de la collection sont accessibles à l'aide d'un index basé sur zéro.

Chaque élément d'un ndarray occupe la même taille de bloc dans la mémoire. Chaque élément d'un ndarray est un objet de type données (appelé dtype).

Tout élément extrait de l'objet ndarray (par découpage) est représenté par un objet Python de l'un des types scalaires du tableau.

Une instance de la classe ndarray peut être construite de différentes façon. Le tableau de base ndarray est créé à l'aide d'une fonction de tableau dans NumPy, comme suit :

In [196]:
numpy.array 

<function numpy.array>

Elle crée un ndarray à partir de n'importe quel objet exposant l'interface array, ou à partir de n'importe quelle méthode qui retourne un array.

In [197]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

array(<class 'object'>, dtype=object)

Le constructeur ci-dessus prend les paramètres suivants :

<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parametre &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>object</b></p>
<p>Tout objet exposant la méthode de l'interface array, renvoie un array, ou toute séquence (imbriquée).</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>dtype</b></p>
<p>Type de données souhaité pour le tableau, facultatif</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>copy</b></p>
<p>Facultatif. Par défaut (true), l'objet est copié.</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>order</b></p>
<p>C (majeure de la ligne) ou F (majeure de la colonne) ou A (quelconque) (par défaut)</p>
</td>
</tr>
<tr>
<td class="ts">5</td>
<td><p><b>subok</b></p>
<p>Par défaut, le tableau retourné est forcé d'être un tableau de classe de base.</p>
</td>
</tr>
<tr>
<td class="ts">6</td>
<td><p><b>ndmin</b></p>
<p>Spécifie les dimensions minimales du tableau résultant</p>
</td>
</tr>
</tbody></table>

Jetez un coup d'œil aux exemples suivants pour mieux comprendre.

In [198]:
import numpy as np 
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [199]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print(a)

[[1 2]
 [3 4]]


In [200]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [201]:
# dtype parameter 
import numpy as np 
a = np.array([1,3, 2, 3],complex) 
print (a)

[1.+0.j 3.+0.j 2.+0.j 3.+0.j]


L'objet ndarray consiste en un segment unidimensionnel contigu de la mémoire de l'ordinateur, associé à un schéma d'indexation qui fait correspondre chaque élément à un emplacement dans le bloc de mémoire. Le bloc de mémoire contient les éléments dans un ordre de rangée majeure (style C) ou un ordre de colonne majeure (style FORTRAN ou MatLab).

### NumPy - Data Types

NumPy prend en charge une variété beaucoup plus grande de types numériques que Python. Le tableau suivant présente les différents types de données scalaires définis dans NumPy.

<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Data Types &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>bool_</b></p>
<p>Boolean (True or False) stored as a byte</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>int_</b></p>
<p>Default integer type (same as C long; normally either int64 or int32)</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>intc</b></p>
<p>Identical to C int (normally int32 or int64)</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>intp</b></p>
<p>Integer used for indexing (same as C ssize_t; normally either int32 or int64)</p>
</td>
</tr>
<tr>
<td class="ts">5</td>
<td><p><b>int8</b></p>
<p>Byte (-128 to 127)</p>
</td>
</tr>
<tr>
<td class="ts">6</td>
<td><p><b>int16</b></p>
<p>Integer (-32768 to 32767)</p>
</td>
</tr>
<tr>
<td class="ts">7</td>
<td><p><b>int32</b></p>
<p>Integer (-2147483648 to 2147483647)</p>
</td>
</tr>
<tr>
<td class="ts">8</td>
<td><p><b>int64</b></p>
<p>Integer (-9223372036854775808 to 9223372036854775807)</p>
</td>
</tr>
<tr>
<td class="ts">9</td>
<td><p><b>uint8</b></p>
<p>Unsigned integer (0 to 255)</p>
</td>
</tr>
<tr>
<td class="ts">10</td>
<td><p><b>uint16</b></p>
<p>Unsigned integer (0 to 65535)</p>
</td>
</tr>
<tr>
<td class="ts">11</td>
<td><p><b>uint32</b></p>
<p>Unsigned integer (0 to 4294967295)</p>
</td>
</tr>
<tr>
<td class="ts">12</td>
<td><p><b>uint64</b></p>
<p>Unsigned integer (0 to 18446744073709551615)</p>
</td>
</tr>
<tr>
<td class="ts">13</td>
<td><p><b>float_</b></p>
<p>Shorthand for float64</p>
</td>
</tr>
<tr>
<td class="ts">14</td>
<td><p><b>float16</b></p>
<p>Half precision float: sign bit, 5 bits exponent, 10 bits mantissa</p>
</td>
</tr>
<tr>
<td class="ts">15</td>
<td><p><b>float32</b></p>
<p>Single precision float: sign bit, 8 bits exponent, 23 bits mantissa</p>
</td>
</tr>
<tr>
<td class="ts">16</td>
<td><p><b>float64</b></p>
<p>Double precision float: sign bit, 11 bits exponent, 52 bits mantissa</p>
</td>
</tr>
<tr>
<td class="ts">17</td>
<td><p><b>complex_</b></p>
<p>Shorthand for complex128</p>
</td>
</tr>
<tr>
<td class="ts">18</td>
<td><p><b>complex64</b></p>
<p>Complex number, represented by two 32-bit floats (real and imaginary components)</p>
</td>
</tr>
<tr>
<td class="ts">19</td>
<td><p><b>complex128</b></p>
<p>Complex number, represented by two 64-bit floats (real and imaginary components)</p>
</td>
</tr>
</tbody></table>

Les types numériques de NumPy sont des instances d'objets dtype (data-type), chacun ayant des caractéristiques uniques. Les dtypes sont disponibles en tant que np.bool_, np.float32, etc.

### Data Type Objects (dtype)

Un objet dtype décrit l'interprétation d'un bloc fixe de mémoire correspondant à un tableau, en fonction des aspects suivants 

    - le type de données (entier, flottant ou objet Python)

    - la taille des données

    - l'ordre des octets (little-endian ou big-endian).

    - Dans le cas d'un type structuré, les noms des champs, le type de données de chaque champ et la partie du bloc de mémoire occupée par chaque champ.

    - Si le type de données est un sous-bloc, sa forme et son type de données.

L'ordre des octets est déterminé en faisant précéder l'objet dtype de '<' ou '>'. '<' signifie que le codage est little-endian (le bit le moins significatif est stocké à la plus petite adresse). '>' signifie que le codage est big-endian (l'octet le plus significatif est stocké dans l'adresse la plus petite).

Un objet dtype est construit à l'aide de la syntaxe suivante :


In [202]:
numpy.dtype(object, align, copy)

NameError: name 'align' is not defined

Les paramètres sont :

    Object − l'objet a convertir en dtype
    Align − si vrai, ajoute du remplissage au champ pour le rendre similaire à la structure C
    Copy − crée une nouvelle copie de l'objet dtype. Si false, le résultat est une référence à l'objet de type de données intégré.


Ci dessous quelques exemples : 

In [ ]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print(dt)

In [ ]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i4')
print(dt) 

In [ ]:
# using endian notation 
import numpy as np 
dt = np.dtype('>i4') 
print(dt)

Les exemples suivants montrent l'utilisation du type de données structuré. Ici, il s'agit de déclarer le nom du champ et le type de données scalaires correspondant.

In [ ]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print(dt)

In [ ]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

In [ ]:
# file name can be used to access content of age column 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['age'])

Les exemples suivants définissent un type de données structuré appelé student avec un champ de type string 'name', un champ de type integer 'age' et un champ de type float 'marks'. Ce type de données est appliqué à l'objet ndarray.

In [ ]:

import numpy as np 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print(student)

In [ ]:
import numpy as np 

student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)
print(a['marks'])

Chaque dtype intégré possède un code de caractère qui l'identifie de manière unique.


    'b' − boolean

    'i' − (signed) integer

    'u' − unsigned integer

    'f' − floating-point

    'c' − complex-floating point

    'm' − timedelta

    'M' − datetime

    'O' − (Python) objects

    'S', 'a' − (byte-)string

    'U' − Unicode

    'V' − raw data (void)


### NumPy - Array Attributes

Dans ce chapitre, nous allons discuter des différents attributs de tableaux de NumPy

##### ndarray.shape
Cet attribut de tableau renvoie un tuple composé des dimensions du tableau. Il peut également être utilisé pour redimensionner le tableau.

###### Exemples

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)

In [ ]:
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]])
print(a, "\n")
a.shape = (3,2) 
print(a,'\n') 
#NumPy also provides a reshape function to resize an array.
a = a.reshape(2, 3)
print(a)

##### ndarray.ndim
Cet attribut de tableau renvoie le nombre de dimensions du tableau.

In [ ]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) 
print(a)

In [ ]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
print(a)
print(a.ndim)

# now reshape it 
b = a.reshape(2,4,3) 
print('\n',b )
print(b.ndim)
# b is having three dimensions

##### numpy.itemsize
Cet attribut de tableau renvoie la longueur de chaque élément du tableau en octets.

In [ ]:
# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int32) 
print(x.itemsize)


##### numpy.flags
Ce attribut renvoie les  elements suivants :

<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Attribute &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>C_CONTIGUOUS (C)</b></p>
<p>The data is in a single, C-style contiguous segment</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>F_CONTIGUOUS (F)</b></p>
<p>The data is in a single, Fortran-style contiguous segment</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>OWNDATA (O)</b></p>
<p>The array owns the memory it uses or borrows it from another object</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>WRITEABLE (W)</b></p>
<p>The data area can be written to. Setting this to False locks the data, making it read-only</p>
</td>
</tr>
<tr>
<td class="ts">5</td>
<td><p><b>ALIGNED (A)</b></p>
<p>The data and all elements are aligned appropriately for the hardware</p>
</td>
</tr>
<tr>
<td class="ts">6</td>
<td><p><b>UPDATEIFCOPY (U)</b></p>
<p>This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array</p>
</td>
</tr>
    </tbody></table>

In [ ]:
import numpy as np 
x = np.array([1,2,3,4,5]) 
print(x.flags)

### NumPy - Array Creation Routines

Un nouvel objet ndarray peut être construit par l'une des routines de création de tableau suivantes ou en utilisant un constructeur ndarray de bas niveau.

#### numpy.empty
Elle crée un tableau non initialisé de forme et du dtype spécifiés. Il utilise le constructeur suivant :

In [ ]:
numpy.empty(shape, dtype = float, order = 'C')

##### Description des paramètres
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>Shape</b></p>
<p>Shape of an empty array in int or tuple of int</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>Dtype</b></p>
<p>Desired output data type. Optional</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>Order</b></p>
<p>'C' for C-style row-major array, 'F' for FORTRAN style column-major array</p>
</td>
</tr>
</tbody></table>

In [ ]:
# Exemple 
import numpy as np 
x = np.empty([3,2], dtype = int) 
print(x)

#Remarque - Les éléments d'un tableau présentent des valeurs aléatoires car ils ne sont pas initialisés.

### numpy.zeros
Renvoie un nouveau tableau de taille spécifiée, rempli de zéros.
Son constructeur est le suivant 

In [ ]:
numpy.zeros(shape, dtype = float, order = 'C')

In [ ]:
# Exemple1
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print(x)

In [ ]:
# Exemple2
import numpy as np 
x = np.zeros((5,), dtype = np.int) 
print(x)

In [ ]:
# Exemple3
# custom type 
import numpy as np 
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(x)

### numpy.ones
    Meme fonctionnement que numpy.zeros, sauf qu'il initialise les champs, non pas à zéro, mais à 1.

In [ ]:
# Exemple 
# custom type 
import numpy as np 
x = np.ones((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(x)

### NumPy - Array From Existing Data
    Dans ce chapitre nous discuterons de comment créer des listes à partir de données existentes.
    
#### numpy.asarray
    Cette fonction est similaire à numpy.array sauf qu'elle a moins de paramètres. Cette routine est utile pour convertir une séquence Python en ndarray.
    Elle a pour contructeur :

In [ ]:
numpy.asarray(a, dtype = None, order = None)

Le constructeur prend les paramètres suivants :
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>a</b></p>
<p>Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>dtype</b></p>
<p>By default, the data type of input data is applied to the resultant ndarray</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>order</b></p>
<p>C (row major) or F (column major). C is default</p>
</td>
</tr>
</tbody></table>

In [ ]:
# Exemple 
#convert list to ndarray 

import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print(a)
a = np.asarray(x, dtype = float) 
print(a)
x = (1,2,3) 
a = np.asarray(x) 
print(a)

In [ ]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print(a)

### numpy.frombuffer
Cette fonction interprète un tampon comme un tableau unidimensionnel. N'importe quel objet qui expose l'interface de tampon est utilisé comme paramètre pour retourner un ndarray. Son constructeur :

In [ ]:
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)

Le constructeur prend les paramètres suivants :
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>buffer</b></p>
<p>Any object that exposes buffer interface</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>dtype</b></p>
<p>Data type of returned ndarray. Defaults to float</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>count</b></p>
<p>The number of items to read, default -1 means all data</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>offset</b></p>
<p>The starting position to read from. Default is 0</p>
</td>
</tr>
</tbody></table>

### numpy.fromiter
Cette fonction construit un objet ndarray à partir de n'importe quel objet itérable. Un nouveau tableau unidimensionnel est retourné par cette fonction. Son contructeur:

In [ ]:
numpy.fromiter(iterable, dtype, count = -1)

Ici, le constructeur prend les paramètres suivants.
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>iterable</b></p>
<p>Any iterable object</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>dtype</b></p>
<p>Data type of resultant array</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>count</b></p>
<p>The number of items to be read from iterator. Default is -1 which means all data to be read</p>
</td>
</tr>
</tbody></table>

In [ ]:
## Exemple

# obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print(x)

### NumPy - Array From Numerical Ranges
Dans ce chapitre, nous allons voir comment créer un tableau à partir de plages numériques.
#### numpy.arange
Cette fonction renvoie un objet ndarray contenant des valeurs uniformément espacées dans une plage donnée. Le format de la fonction est le suivant :

In [ ]:
numpy.arange(start, stop, step, dtype)

Ici, le constructeur prend les paramètres suivants.
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>start</b></p>
<p>The start of an interval. If omitted, defaults to 0</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>stop</b></p>
<p>The end of an interval (not including this number)</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>step</b></p>
<p>Spacing between values, default is 1</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>dtype</b></p>
<p>Data type of resulting ndarray. If not given, data type of input is used</p>
</td>
</tr>
</tbody></table>

In [ ]:
# Exemple
# start and stop parameters set 
import numpy as np 
x = np.arange(10,20,2, dtype = float) 
print(x)

###  numpy.linspace
Cette fonction est similaire à la fonction arange(). Dans cette fonction, au lieu de la taille du pas, on spécifie le nombre de valeurs régulièrement espacées entre les intervalles. L'utilisation de cette fonction est la suivante :

In [203]:
numpy.linspace(start, stop, num, endpoint, retstep, dtype)

NameError: name 'start' is not defined

Le constructeur prend les paramètres suivants :
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>start</b></p>
<p>The starting value of the sequence</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>stop</b></p>
<p>The end value of the sequence, included in the sequence if endpoint set to true</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>num</b></p>
<p>The number of evenly spaced samples to be generated. Default is 50</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>endpoint</b></p>
<p>True by default, hence the stop value is included in the sequence. If false, it is not included</p>
</td>
</tr>
<tr>
<td class="ts">5</td>
<td><p><b>retstep</b></p>
<p>If true, returns samples and step between the consecutive numbers</p>
</td>
</tr>
<tr>
<td class="ts">6</td>
<td><p><b>dtype</b></p>
<p>Data type of output <b>ndarray</b></p>
</td>
</tr>
</tbody></table>

In [ ]:
#Exemples

import numpy as np 
x = np.linspace(10,20,5) 
print(x)

In [ ]:
# endpoint set to false 
import numpy as np 
x = np.linspace(10,20, 5, endpoint = False) 
print(x)

In [ ]:
# find retstep value 
import numpy as np 

x = np.linspace(1,2,5, retstep = True) 
print(x)
# retstep here is 0.25

### numpy.logspace
Cette fonction renvoie un objet ndarray qui contient les nombres qui sont uniformément espacés sur une échelle logarithmique. Les points de départ et d'arrivée de l'échelle sont des indices de la base, généralement 10.
Son constructeur :

In [ ]:
numpy.logspace(start, stop, num, endpoint, base, dtype)

Les paramètres du constructeur : 
<table>
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>start</b></p>
<p>The starting point of the sequence is base<sup>start</sup></p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>stop</b></p>
<p>The final value of sequence is base<sup>stop</sup></p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>num</b></p>
<p>The number of values between the range. Default is 50</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>endpoint</b></p>
<p>If true, stop is the last value in the range</p>
</td>
</tr>
<tr>
<td class="ts">5</td>
<td><p><b>base</b></p>
<p>Base of log space, default is 10</p>
</td>
</tr>
<tr>
<td class="ts">6</td>
<td><p><b>dtype</b></p>
<p>Data type of output array. If not given, it depends upon other input arguments</p>
</td>
</tr>
</tbody>
<table/>

In [ ]:
# Exemples

import numpy as np 
# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) 
print(a)

In [ ]:
# set base of log space to 2 
import numpy as np 
a = np.logspace(1,10,num = 10, base = 2) 
print(a)

### NumPy - Indexing & Slicing

    Le contenu de l'objet ndarray peut être accédé et modifié par indexation ou découpage, tout comme les objets conteneurs intégrés de Python.

Comme mentionné précédemment, les éléments de l'objet ndarray suivent un index basé sur zéro. Trois types de méthodes d'indexation sont disponibles : l'accès aux champs, le découpage de base et l'indexation avancée.

Le découpage de base est une extension du concept de base de Python de découpage à n dimensions. Un objet de découpage Python est construit en donnant les paramètres start, stop et step à la fonction intégrée de découpage. Cet objet slice est passé au tableau pour extraire une partie du tableau.

In [ ]:
# Exemples

import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print(a[s])

Dans l'exemple ci-dessus, un objet ndarray est préparé par la fonction arange(). Ensuite, un objet slice est défini avec les valeurs start, stop, et step 2, 7, et 2 respectivement. Lorsque cet objet slice est passé à l'objet ndarray, une partie de celui-ci, commençant à l'indice 2 jusqu'à 7 avec un pas de 2, est découpée en tranches.

Le même résultat peut également être obtenu en donnant les paramètres de découpage séparés par deux points : (start:stop:step) directement à l'objet ndarray.
Le contenu de l'objet ndarray peut être accédé et modifié par indexation ou découpage, tout comme les objets conteneurs intégrés de Python.

In [ ]:
# Exemple 
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
print(b)

Si un seul paramètre est placé, un seul élément correspondant à l'index sera retourné. Si un : est inséré devant, tous les éléments à partir de cet index seront extraits. Si deux paramètres (avec un : entre eux) sont utilisés, les éléments entre les deux index (sans inclure l'index d'arrêt) avec le pas par défaut un sont découpés.
Le contenu de l'objet ndarray peut être accédé et modifié par indexation ou découpage, tout comme les objets conteneurs intégrés de Python.

In [ ]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
print(b)

In [ ]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print(a[2:])

# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print(a[2:5], '\n')

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a, '\n')

# slice items starting from index
print(a[1:])

In [ ]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print(a)
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1] )
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...] )
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:]

### NumPy - Advanced Indexing
Il est possible d'effectuer une sélection dans ndarray qui est une séquence non-tuple, un objet ndarray de type entier ou booléen, ou un tuple dont au moins un élément est un objet séquence. L'indexation avancée renvoie toujours une copie des données. En revanche, le découpage en tranches ne présente qu'une vue.

Il existe deux types d'indexation avancée - Integer et Boolean.

#### Integer Indexing

Ce mécanisme permet de sélectionner n'importe quel élément arbitraire d'un tableau en fonction de son index à N dimensions. Chaque tableau d'entiers représente le nombre d'index dans cette dimension. Lorsque l'index est constitué d'autant de tableaux d'entiers que de dimensions du tableau nd cible, cela devient simple.

Dans l'exemple suivant, un élément de la colonne spécifiée de chaque ligne de l'objet ndarray est sélectionné. Par conséquent, l'index de ligne contient tous les numéros de ligne, et l'index de colonne spécifie l'élément à sélectionner.

In [ ]:
# Exemples
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print (y)

La sélection comprend les éléments situés à (0,0), (1,1) et (2,0) du premier tableau.

Dans l'exemple suivant, les éléments placés aux coins d'un tableau 4X3 sont sélectionnés. Les indices de ligne de la sélection sont [0, 0] et [3, 3] tandis que les indices de colonne sont [0, 2] et [0, 2].

In [ ]:
# Exemples 

import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print( 'Our array is:' )
print (x) 
print ('\n') 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print ('The corner elements of this array are:') 
print (y)

La sélection résultante est un objet ndarray contenant des éléments d'angle.

L'indexation avancée et de base peut être combinée en utilisant une tranche ( :) ou une ellipse (...) avec un tableau d'index. L'exemple suivant utilise slice pour la ligne et advanced index pour la colonne. Le résultat est le même lorsque la tranche est utilisée pour les deux. Mais l'index avancé résulte en une copie et peut avoir une disposition de mémoire différente.

In [ ]:
# Exemples 
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Our array is:') 
print (x) 
print ('\n')  

# slicing 
z = x[1:4,1:3] 

print ('After slicing, our array becomes:') 
print (z) 
print ('\n' ) 

# using advanced index for column 
y = x[1:4,[1,2]] 

print ('Slicing using advanced index for column:') 
print (y)

#### Boolean Array Indexing
Ce type d'indexation avancée est utilisé lorsque l'objet résultant est censé être le résultat d'opérations booléennes, telles que des opérateurs de comparaison.

In [ ]:
# Exemples

import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Our array is:') 
print (x) 
print ('\n')  

# Now we will print the items greater than 5 
print ('The items greater than 5 are:') 
print (x[x > 5])

In [ ]:
# In this example, NaN (Not a Number) elements are omitted by using ~ (complement operator).
import numpy as np 
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a)
print (a[~np.isnan(a)])

In [ ]:
# The following example shows how to filter out the non-complex elements from an array.
import numpy as np 
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print( a[np.iscomplex(a)])

### NumPy - Broadcasting
Le terme "brodcastion" (diffusion) fait référence à la capacité de NumPy à traiter des tableaux de formes différentes lors des opérations arithmétiques. Les opérations arithmétiques sur les tableaux sont généralement effectuées sur les éléments correspondants. Si deux tableaux sont exactement de la même forme, alors ces opérations sont effectuées sans problème.

In [ ]:
# Exemples
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

Si les dimensions de deux tableaux sont dissemblables, les opérations d'élément à élément ne sont pas possibles. Cependant, les opérations sur des tableaux de formes non similaires sont toujours possibles dans NumPy, grâce à la capacité de diffusion. Le tableau le plus petit est diffusé à la taille du tableau le plus grand afin qu'ils aient des formes compatibles.

La diffusion est possible si les règles suivantes sont respectées : 
    - Le tableau avec un ndim plus petit que le tableau avec un ndim plus grand.

    - Le tableau ayant un ndim plus petit que l'autre est précédé de '1' dans sa forme.

    - La taille dans chaque dimension de la forme de sortie est le maximum des tailles d'entrée dans cette dimension.

    - Une entrée peut être utilisée dans le calcul, si sa taille dans une dimension particulière correspond à la taille de la sortie ou si sa valeur est exactement 1.

    - Si une entrée a une dimension de 1, la première entrée de données dans cette dimension est utilisée pour tous les calculs dans cette dimension.

    - On dit d'un ensemble de tableaux qu'il est diffusable si les règles ci-dessus produisent un résultat valide et si l'une des conditions suivantes est vraie

    - Les tableaux ont exactement la même forme.

    - Les tableaux ont le même nombre de dimensions et la longueur de chaque dimension est soit une longueur commune, soit 1.

    - Un tableau ayant trop peu de dimensions peut voir sa forme précédée d'une dimension de longueur 1, de sorte que la propriété mentionnée ci-dessus soit vraie.

Le programme suivant montre un exemple de diffusion :

In [ ]:
# Exemples
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print( a) 
print ('\n')  
   
print ('Second array:') 
print (b) 
print ('\n')  
   
print ('First Array + Second Array') 
print( a + b)

La figure suivante montre comment le tableau b est diffusé pour devenir compatible avec a.
<img src="array.jpg">

### 

<div class="mui-col-md-6 tutorial-content">
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">NumPy - Manipulation de tableau</font></font></h1>
<hr>
<div id="google-top-ads">

<br>
<div class="clearer"></div>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Plusieurs routines sont disponibles dans le package NumPy pour la manipulation d'éléments dans l'objet ndarray. </font><font style="vertical-align: inherit;">Ils peuvent être classés dans les types suivants -</font></font></p>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Changer de forme</font></font></h2>
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sr.No.</font></font></th>
<th style="text-align:center;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Forme et description</font></font></th>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1</font></font></td>
<td><a href="/numpy/numpy_reshape.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">remodeler</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Donne une nouvelle forme à un tableau sans modifier ses données</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2</font></font></td>
<td><a href="/numpy/numpy_ndarray_flat.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">plat</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Un itérateur 1-D sur le tableau</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3</font></font></td>
<td><a href="/numpy/numpy_ndarray_flatten.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">aplatir</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Renvoie une copie du tableau réduit en une dimension</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4</font></font></td>
<td><a href="/numpy/numpy_ndarray_ravel.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">effilochage</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Renvoie un tableau aplati contigu</font></font></p>
</td>
</tr>
</tbody></table>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Opérations de transposition</font></font></h2>
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sr.No.</font></font></th>
<th style="text-align:center;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Description d'opération</font></font></th>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1</font></font></td>
<td><a href="/numpy/numpy_transpose.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">transposer</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Permute les dimensions d'un tableau</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2</font></font></td>
<td><a href="/numpy/numpy_ndarray_t.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ndarray.T</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Identique à self.transpose()</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3</font></font></td>
<td><a href="/numpy/numpy_rollaxis.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">axe de roulis</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Fait reculer l'axe spécifié</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4</font></font></td>
<td><a href="/numpy/numpy_swapaxes.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">swapaxes</font></font></a>
<p>Interchanges the two axes of an array</p>
</td>
</tr>
</tbody></table>
<h2>Changing Dimensions</h2>
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Dimension &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_broadcast.htm">broadcast</a>
<p>Produces an object that mimics broadcasting</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_broadcast_to.htm">broadcast_to</a>
<p>Broadcasts an array to a new shape</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_expand_dims.htm">expand_dims</a>
<p>Expands the shape of an array</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_squeeze.htm">squeeze</a>
<p>Removes single-dimensional entries from the shape of an array</p>
</td>
</tr>
</tbody></table>
<h2>Joining Arrays</h2>
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Array &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_concatenate.htm">concatenate</a>
<p>Joins a sequence of arrays along an existing axis</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_stack.htm">stack</a>
<p>Joins a sequence of arrays along a new axis</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_hstack.htm">hstack</a>
<p>Stacks arrays in sequence horizontally (column wise)</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_vstack.htm">vstack</a>
<p>Stacks arrays in sequence vertically (row wise)</p>
</td>
</tr>
</tbody></table>
<h2>Splitting Arrays</h2>
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Array &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_split.htm">split</a>
<p>Splits an array into multiple sub-arrays</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_hsplit.htm">hsplit</a>
<p>Splits an array into multiple sub-arrays horizontally (column-wise)</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_vsplit.htm">vsplit</a>
<p>Splits an array into multiple sub-arrays vertically (row-wise)</p>
</td>
</tr>
</tbody></table>
<h2>Adding / Removing Elements</h2>
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Element &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_resize.htm">resize</a>
<p>Returns a new array with the specified shape</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_append.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ajouter</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ajoute les valeurs à la fin d'un tableau</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3</font></font></td>
<td><a href="/numpy/numpy_insert.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">insérer</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Insère les valeurs le long de l'axe donné avant les indices donnés</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4</font></font></td>
<td><a href="/numpy/numpy_delete.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">effacer</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Renvoie un nouveau tableau avec des sous-tableaux le long d'un axe supprimés</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5</font></font></td>
<td><a href="/numpy/numpy_unique.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">unique</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Trouve les éléments uniques d'un tableau</font></font></p>
</td>
</tr>
</tbody></table>


###  NumPy - Mathematical Functions
Tout à fait compréhensible, NumPy contient un grand nombre d'opérations mathématiques diverses. NumPy fournit des fonctions trigonométriques standard, des fonctions pour les opérations arithmétiques, la gestion des nombres complexes, etc.

#### Fonctions trigonométriques
NumPy a des fonctions trigonométriques standard qui renvoient des rapports trigonométriques pour un angle donné en radians.

In [ ]:
# Exemples 
import numpy as np 
a = np.array([0,30,45,60,90]) 

print ('Sine of different angles:') 
# Convert to radians by multiplying with pi/180 
print (np.sin(a*np.pi/180)) 
print ('\n')  

print ('Cosine values for angles in array:') 
print (np.cos(a*np.pi/180)) 
print ('\n')

print ('Tangent values for given angles:') 
print (np.tan(a*np.pi/180)) 

Les fonctions arcsin, arcos et arctan renvoient l'inverse trigonométrique de sin, cos et tan de l'angle donné. Le résultat de ces fonctions peut être vérifié par la fonction numpy.degrees() en convertissant les radians en degrés.

#### Fonctions d'arrondi
numpy.around()
Il s'agit d'une fonction qui renvoie la valeur arrondie à la précision souhaitée. La fonction prend les paramètres suivants.


In [ ]:
numpy.around(a,decimals)
# decimals - Le nombre de décimales à arrondir. La valeur par défaut est 0. S'il est négatif, l'entier est arrondi pour se placer à gauche de la virgule décimale

In [ ]:
# Exemple
import numpy as np 
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print ('Original array:') 
print(a)
print ('\n')  

print ('After rounding:') 
print( np.around(a)) 
print( np.around(a, decimals = 1) )
print (np.around(a, decimals = -1))

#### numpy.floor()
Cette fonction renvoie le plus grand entier non supérieur au paramètre d'entrée. Le plancher du scalaire x est le plus grand entier i , tel que i <= x . Notez qu'en Python, le revêtement de sol est toujours arrondi à 0.

In [204]:
# Exemples 
import numpy as np 
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print( 'The given array:') 
print(a)
print ('\n' ) 

print ('The modified array:') 
print (np.floor(a))

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-2.  1. -1.  0. 10.]


#### numpy.ceil()
La fonction ceil() renvoie le plafond d'une valeur d'entrée, c'est-à-dire que le plafond du scalaire x est le plus petit entier i , tel que i >= x.

Exemple

In [205]:
import numpy as np 
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print ('The given array:') 
print( a) 
print ('\n' ) 

print ('The modified array:') 
print (np.ceil(a))

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-1.  2. -0.  1. 10.]


<div class="mui-col-md-6 tutorial-content">
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">NumPy - Opérations arithmétiques</font></font></h1>
<hr>
<div class="clearer"></div>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Les tableaux d'entrée pour effectuer des opérations arithmétiques telles que ajouter(), soustraire(), multiplier() et diviser() doivent avoir la même forme ou doivent être conformes aux règles de diffusion des tableaux.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exemple</font></font></h3>

In [206]:
import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print ('First array:' )
print (a) 
print ('\n')  

print ('Second array:') 
b = np.array([10,10,10]) 
print( b) 
print ('\n' ) 

print ('Add the two arrays:') 
print (np.add(a,b)) 
print ('\n')  

print ('Subtract the two arrays:' )
print (np.subtract(a,b) )
print ('\n' ) 

print ('Multiply the two arrays:' )
print (np.multiply(a,b) )
print ('\n')  

print ('Divide the two arrays:') 
print (np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Voyons maintenant quelques-unes des autres fonctions arithmétiques importantes disponibles dans NumPy.</font></font></p>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.reciprocal()</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cette fonction renvoie l'inverse de l'argument, élément par élément. </font><font style="vertical-align: inherit;">Pour les éléments dont les valeurs absolues sont supérieures à 1, le résultat est toujours 0 en raison de la manière dont Python gère la division entière. </font><font style="vertical-align: inherit;">Pour l'entier 0, un avertissement de débordement est émis.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exemple</font></font></h3>


In [207]:
import numpy as np 
a = np.array([0.25, 1.33, 1, 0, 100]) 

print ('Our array is:' )
print (a )
print ('\n'  )

print ('After applying reciprocal function:' )
print (np.reciprocal(a) )
print ('\n')  

b = np.array([100], dtype = int) 
print ('The second array is:' )
print (b) 
print ('\n')  

print ('After applying reciprocal function:') 
print( np.reciprocal(b) )

Our array is:
[  0.25   1.33   1.     0.   100.  ]


After applying reciprocal function:
[4.        0.7518797 1.              inf 0.01     ]


The second array is:
[100]


After applying reciprocal function:
[0]


<ipython-input-207-17687b4fb082>:9: RuntimeWarning: divide by zero encountered in reciprocal
  print (np.reciprocal(a) )


<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.power()</font></font></h2><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cette fonction traite les éléments du premier tableau d'entrée comme une base et le renvoie à la puissance de l'élément correspondant du deuxième tableau d'entrée.</font></font></p>


In [208]:
import numpy as np 
a = np.array([10,100,1000]) 

print ('Our array is:' )
print (a )
print ('\n'  )

print ('Applying power function:' )
print (np.power(a,2)) 
print ('\n')  

print ('Second array:') 
b = np.array([1,2,3]) 
print (b) 
print ('\n')  

print ('Applying power function again:') 
print (np.power(a,b))

Our array is:
[  10  100 1000]


Applying power function:
[    100   10000 1000000]


Second array:
[1 2 3]


Applying power function again:
[        10      10000 1000000000]


<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.mod()</font></font></h2><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cette fonction renvoie le reste de la division des éléments correspondants dans le tableau d'entrée. </font><font style="vertical-align: inherit;">La fonction </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.remainder()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> produit également le même résultat.</font></font></p

In [209]:
import numpy as np 
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Second array:') 
print (b) 
print ('\n')  

print ('Applying mod() function:') 
print (np.mod(a,b) )
print ('\n')  

print ('Applying remainder() function:') 
print (np.remainder(a,b)) 

First array:
[10 20 30]


Second array:
[3 5 7]


Applying mod() function:
[1 0 2]


Applying remainder() function:
[1 0 2]


<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Les fonctions suivantes sont utilisées pour effectuer des opérations sur un tableau avec des nombres complexes.</font></font></p>
<ul class="list">
<li><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.real()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> - renvoie la partie réelle de l'argument de type de données complexe.</font></font></p></li>
<li><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.imag()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> - renvoie la partie imaginaire de l'argument de type de données complexe.</font></font></p></li>
<li><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.conj()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> − renvoie le conjugué complexe, qui est obtenu en changeant le signe de la partie imaginaire.</font></font></p></li>
<li><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.angle()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> − renvoie l'angle de l'argument complexe. </font><font style="vertical-align: inherit;">La fonction a un paramètre de degré. </font><font style="vertical-align: inherit;">Si vrai, l'angle en degré est renvoyé, sinon l'angle est en radians.</font></font></p></li>
</ul>

In [210]:
import numpy as np 
a = np.array([-5.6j, 0.2j, 11. , 1+1j]) 

print ('Our array is:') 
print( a) 
print ('\n')  

print ('Applying real() function:') 
print (np.real(a) )
print ('\n')  

print ('Applying imag() function:') 
print (np.imag(a)) 
print ('\n' ) 

print ('Applying conj() function:') 
print (np.conj(a)) 
print ('\n')  

print ('Applying angle() function:') 
print (np.angle(a)) 
print ('\n')  

print ('Applying angle() function again (result in degrees)') 
print( np.angle(a, deg = True))

Our array is:
[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]


Applying real() function:
[-0.  0. 11.  1.]


Applying imag() function:
[-5.6  0.2  0.   1. ]


Applying conj() function:
[-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


Applying angle() function:
[-1.57079633  1.57079633  0.          0.78539816]


Applying angle() function again (result in degrees)
[-90.  90.   0.  45.]


<div class="mui-col-md-6 tutorial-content">
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">NumPy - Fonctions statistiques</font></font></h1>

<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">NumPy a quelques fonctions statistiques utiles pour trouver l'écart type et la variance minimum, maximum, percentile, etc. à partir des éléments donnés dans le tableau. </font><font style="vertical-align: inherit;">Les fonctions sont expliquées comme suit −</font></font></p>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.amin() et numpy.amax()</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ces fonctions renvoient le minimum et le maximum des éléments du tableau donné le long de l'axe spécifié.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exemple</font></font></h3>

In [211]:
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('Our array is:') 
print( a ) 
print ('\n')  

print ('Applying amin() function:' )
print (np.amin(a,1)) 
print ('\n')  

print ('Applying amin() function again:' )
print (np.amin(a,0)) 
print ('\n')  

print ('Applying amax() function:') 
print (np.amax(a)) 
print ('\n')  

print ('Applying amax() function again:') 
print (np.amax(a, axis = 0))

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function:
[3 3 2]


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() function again:
[8 7 9]


<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.ptp()</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La fonction </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.ptp()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> renvoie la plage (maximum-minimum) de valeurs le long d'un axe.</font></font></p>

In [212]:
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('Our array is:') 
print( a )
print ('\n')  

print ('Applying ptp() function:') 
print (np.ptp(a)) 
print ('\n')  

print ('Applying ptp() function along axis 1:') 
print (np.ptp(a, axis = 1)) 
print ('\n')   

print ('Applying ptp() function along axis 0:')
print (np.ptp(a, axis = 0) )

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying ptp() function:
7


Applying ptp() function along axis 1:
[4 5 7]


Applying ptp() function along axis 0:
[6 3 6]


<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.percentile()</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Le centile (ou un centile) est une mesure utilisée dans les statistiques indiquant la valeur en dessous de laquelle tombe un pourcentage donné d'observations dans un groupe d'observations. </font><font style="vertical-align: inherit;">La fonction </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.percentile()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> prend les arguments suivants.</font></font></p>
<pre class="result notranslate">numpy.percentile(a, q, axis)
</pre>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Où,</font></font></p>
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;width:10%"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sr.No.</font></font></th>
<th style="text-align:center;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Argument &amp; Description</font></font></th>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">une</font></font></b></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tableau d'entrée</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">q</font></font></b></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Le centile à calculer doit être compris entre 0 et 100</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">axe</font></font></b></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">L'axe le long duquel le centile doit être calculé</font></font></p>
</td>
</tr>
</tbody></table>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exemple</font></font></h3>


In [213]:
import numpy as np 
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print ('Our array is:' )
print (a )
print( '\n' ) 

print ('Applying percentile() function:') 
print (np.percentile(a,50)) 
print ('\n')  

print ('Applying percentile() function along axis 1:') 
print (np.percentile(a,50, axis = 1)) 
print ('\n')  

print ('Applying percentile() function along axis 0:') 
print (np.percentile(a,50, axis = 0))

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying percentile() function:
50.0


Applying percentile() function along axis 1:
[40. 20. 60.]


Applying percentile() function along axis 0:
[50. 40. 60.]


<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.median()</font></font></h2>
<p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La médiane</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> est définie comme la valeur séparant la moitié supérieure d'un échantillon de données de la moitié inférieure. </font><font style="vertical-align: inherit;">La fonction </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.median()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> est utilisée comme indiqué dans le programme suivant.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exemple</font></font></h3>

In [214]:
import numpy as np 
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print ('Our array is:' )
print( a )
print ('\n'  )

print ('Applying median() function:' )
print (np.median(a) )
print ('\n'  )

print ('Applying median() function along axis 0:' )
print (np.median(a, axis = 0) )
print ('\n')  
 
print ('Applying median() function along axis 1:') 
print (np.median(a, axis = 1))

Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


Applying median() function:
65.0


Applying median() function along axis 0:
[50. 90. 60.]


Applying median() function along axis 1:
[65. 80. 60.]


<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.mean()</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La moyenne arithmétique est la somme des éléments le long d'un axe divisée par le nombre d'éléments. </font><font style="vertical-align: inherit;">La fonction </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.mean()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> renvoie la moyenne arithmétique des éléments du tableau. </font><font style="vertical-align: inherit;">Si l'axe est mentionné, il est calculé le long de celui-ci.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exemple</font></font></h3>

In [215]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print( a) 
print ('\n')  

print ('Applying mean() function:') 
print (np.mean(a) )
print ('\n')  

print ('Applying mean() function along axis 0:' )
print (np.mean(a, axis = 0)) 
print ('\n')  

print ('Applying mean() function along axis 1:') 
print (np.mean(a, axis = 1))

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying mean() function:
3.6666666666666665


Applying mean() function along axis 0:
[2.66666667 3.66666667 4.66666667]


Applying mean() function along axis 1:
[2. 4. 5.]


<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.average()</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La moyenne pondérée est une moyenne résultant de la multiplication de chaque composante par un facteur reflétant son importance. </font><font style="vertical-align: inherit;">La fonction </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">numpy.average()</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> calcule la moyenne pondérée des éléments d'un tableau en fonction de leur poids respectif donné dans un autre tableau. </font><font style="vertical-align: inherit;">La fonction peut avoir un paramètre d'axe. </font><font style="vertical-align: inherit;">Si l'axe n'est pas spécifié, le tableau est aplati.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">En considérant un tableau [1,2,3,4] et les poids correspondants [4,3,2,1], la moyenne pondérée est calculée en additionnant le produit des éléments correspondants et en divisant la somme par la somme des poids.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Moyenne pondérée = (1*4+2*3+3*2+4*1)/(4+3+2+1)</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exemple</font></font></h3>

In [216]:
import numpy as np 
a = np.array([1,2,3,4]) 

print ('Our array is:') 
print( a) 
print ('\n')  

print ('Applying average() function:') 
print (np.average(a)) 
print ('\n')  

# this is same as mean when weight is not specified 
wts = np.array([4,3,2,1]) 

print ('Applying average() function again:') 
print (np.average(a,weights = wts) )
print( '\n')  

# Returns the sum of weights, if the returned parameter is set to True. 
print ('Sum of weights') 
print (np.average([1,2,3, 4],weights = [4,3,2,1], returned = True))

Our array is:
[1 2 3 4]


Applying average() function:
2.5


Applying average() function again:
2.0


Sum of weights
(2.0, 10.0)


<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Dans un tableau multidimensionnel, l'axe de calcul peut être spécifié.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exemple</font></font></h3>


In [217]:
import numpy as np 
a = np.arange(6).reshape(3,2) 

print ('Our array is:') 
print( a )
print ('\n')  

print ('Modified array:') 
wt = np.array([3,5]) 
print (np.average(a, axis = 1, weights = wt)) 
print ('\n')  

print ('Modified array:') 
print (np.average(a, axis = 1, weights = wt, returned = True))

Our array is:
[[0 1]
 [2 3]
 [4 5]]


Modified array:
[0.625 2.625 4.625]


Modified array:
(array([0.625, 2.625, 4.625]), array([8., 8., 8.]))


<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Écart-type</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">L'écart type est la racine carrée de la moyenne des écarts carrés par rapport à la moyenne. </font><font style="vertical-align: inherit;">La formule de l'écart type est la suivante&nbsp;:</font></font></p>
<pre class="result notranslate">std = sqrt(mean(abs(x - x.mean())**2))
</pre>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Si le tableau est [1, 2, 3, 4], alors sa moyenne est de 2,5. </font><font style="vertical-align: inherit;">Par conséquent, les écarts au carré sont [2,25, 0,25, 0,25, 2,25] et la racine carrée de sa moyenne divisée par 4, c'est-à-dire que sqrt (5/4) est 1.1180339887498949.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exemple</font></font></h3>

In [218]:
import numpy as np 
print (np.std([1,2,3,4]))

1.118033988749895


<h2>Variance</h2>
<p>La variance est la moyenne des écarts au carré, c'est-à-dire <b>mean(abs(x - x.mean())**2)</b>. En d'autres termes, l'écart-type est la racine carrée de la variance.</p>
<h3>Example</h3>

In [219]:
import numpy as np 
print (np.var([1,2,3,4]))

1.25


<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">NumPy - Fonctions de tri, de recherche et de comptage</font></font></h1>
<p>Une variété de fonctions liées au tri sont disponibles dans NumPy. Ces fonctions de tri mettent en œuvre différents algorithmes de tri, chacun d'entre eux étant caractérisé par la vitesse d'exécution, les performances dans le pire des cas, l'espace de travail requis et la stabilité des algorithmes. Le tableau suivant présente la comparaison de trois algorithmes de tri.</p>
<table style="text-align:center" class="table table-bordered">
<tr>
<th style="text-align:center;">kind</th>
<th style="text-align:center;">speed</th>
<th style="text-align:center;">worst case</th>
<th style="text-align:center;">work space</th>
<th style="text-align:center;">stable</th>
</tr>
<tr>
<td>‘quicksort’</td>
<td>1</td>
<td>O(n^2)</td>
<td>0</td>
<td>no</td>
</tr>
<tr>
<td>‘mergesort’</td>
<td>2</td>
<td>O(n*log(n))</td>
<td>~n/2</td>
<td>yes</td>
</tr>
<tr>
<td>‘heapsort’</td>
<td>3</td>
<td>O(n*log(n))</td>
<td>0</td>
<td>no</td>
</tr>
</table>
<h2>numpy.sort()</h2>
<p>La fonction sort() renvoie une copie triée du tableau d'entrée. Elle possède les paramètres suivants &minus;</p>
<pre class="result notranslate">
numpy.sort(a, axis, kind, order)
</pre>
<p>Where,</p>
<table class="table table-bordered">
<tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>a</b></p>
<p>Array to be sorted</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>axis</b></p>
<p>The axis along which the array is to be sorted. If none, the array is flattened, sorting on the last axis</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>kind</b></p>
<p>Default is quicksort</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>order</b></p>
<p>If the array contains fields, the order of fields to be sorted</p>
</td>
</tr>
</table>
<h3>Exemple</h3>

In [220]:
import numpy as np  
a = np.array([[3,7],[9,1]]) 

print ('Our array is:' )
print (a )
print ('\n')

print ('Applying sort() function:') 
print (np.sort(a)) 
print ('\n')
  
print ('Sort along axis 0:' )
print (np.sort(a, axis = 0)) 
print ('\n' ) 

# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt) 

print ('Our array is:') 
print (a) 
print ('\n' ) 

print ('Order by name:') 
print (np.sort(a, order = 'name'))

Our array is:
[[3 7]
 [9 1]]


Applying sort() function:
[[3 7]
 [1 9]]


Sort along axis 0:
[[3 1]
 [9 7]]


Our array is:
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


Order by name:
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]



<h2>numpy.argsort()</h2>

<p>La fonction numpy.argsort() effectue un tri indirect sur le tableau d'entrée, le long de l'axe donné et en utilisant un type de tri spécifié pour renvoyer le tableau d'indices de données. Ce tableau d'indices est utilisé pour construire le tableau trié.<p/>
<h3>Exemple</h3>

In [221]:
import numpy as np 
x = np.array([3, 1, 2]) 

print ('Our array is:') 
print( x) 
print ('\n')  

print ('Applying argsort() to x:') 
y =( np.argsort(x)) 
print( y) 
print ('\n' ) 

print ('Reconstruct original array in sorted order:') 
print( x[y]) 
print ('\n')  

print ('Reconstruct the original array using loop:') 
for i in y: 
    print(x[i])

Our array is:
[3 1 2]


Applying argsort() to x:
[1 2 0]


Reconstruct original array in sorted order:
[1 2 3]


Reconstruct the original array using loop:
1
2
3


<h2>numpy.lexsort()</h2>

<p>La fonction effectue un tri indirect à l'aide d'une séquence de touches. Les clés peuvent être vues comme une colonne dans une feuille de calcul. La fonction renvoie un tableau d'indices, à l'aide duquel les données triées peuvent être obtenues. Notez que la dernière clé se trouve être la clé primaire du tri.<p/>
<h3>Exemple</h3>

In [222]:
import numpy as np 

nm = ('raju','anil','ravi','amar') 
dv = ('f.y.', 's.y.', 's.y.', 'f.y.') 
ind = np.lexsort((dv,nm)) 

print ('Applying lexsort() function:') 
print (ind) 
print ('\n')  

print ('Use this index to get sorted data:') 
print ([nm[i] + ", " + dv[i] for i in ind] )

Applying lexsort() function:
[3 1 0 2]


Use this index to get sorted data:
['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']


<p>Le module NumPy a un certain nombre de fonctions pour rechercher à l'intérieur d'un tableau. Des fonctions pour trouver le maximum, le minimum ainsi que les éléments satisfaisant une condition donnée sont disponibles.</p>

<h2>numpy.argmax() et numpy.argmin()</h2>

<p>Ces deux fonctions renvoient les indices des éléments maximum et minimum respectivement le long de l'axe donné.<p/>
<h3>Exemple</h3>

In [223]:
import numpy as np 
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print( 'Our array is:') 
print (a) 
print ('\n' )

print ('Applying argmax() function:' )
print (np.argmax(a) )
print ('\n')  

print ('Index of maximum number in flattened array') 
print (a.flatten()) 
print ('\n'  )

print ('Array containing indices of maximum along axis 0:') 
maxindex = np.argmax(a, axis = 0) 
print( maxindex) 
print ('\n')  

print ('Array containing indices of maximum along axis 1:') 
maxindex = np.argmax(a, axis = 1) 
print (maxindex )
print ('\n')  

print ('Applying argmin() function:') 
minindex = np.argmin(a) 
print (minindex )
print ('\n' ) 
   
print ('Flattened array:' )
print (a.flatten()[minindex]) 
print ('\n')  

print ('Flattened array along axis 0:') 
minindex = np.argmin(a, axis = 0) 
print (minindex)
print ('\n')

print ('Flattened array along axis 1:') 
minindex = np.argmin(a, axis = 1) 
print (minindex)

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying argmax() function:
7


Index of maximum number in flattened array
[30 40 70 80 20 10 50 90 60]


Array containing indices of maximum along axis 0:
[1 2 0]


Array containing indices of maximum along axis 1:
[2 0 1]


Applying argmin() function:
5


Flattened array:
10


Flattened array along axis 0:
[0 1 1]


Flattened array along axis 1:
[0 2 0]


### numpy.nonzero()
La fonction numpy.nonzero() renvoie les indices des éléments non nuls dans le tableau d'entrée.



In [224]:
import numpy as np 
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 

print ('Our array is:') 
print( a )
print( '\n')  

print ('Applying nonzero() function:' )
print (np.nonzero (a))

Our array is:
[[30 40  0]
 [ 0 20 10]
 [50  0 60]]


Applying nonzero() function:
(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))


### numpy.where()
La fonction where() renvoie les indices des éléments dans un tableau d'entrée où la condition donnée est satisfaite.

#### Exemple

In [225]:
import numpy as np 
x = np.arange(9.).reshape(3, 3) 

print( 'Our array is:' )
print (x  )

print ('Indices of elements > 3' )
y = (np.where(x > 3) )
print( y ) 

print ('Use these indices to get elements satisfying the condition') 
print( x[y])

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Indices of elements > 3
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
Use these indices to get elements satisfying the condition
[4. 5. 6. 7. 8.]


### numpy.extract()
La fonction extract() renvoie les éléments satisfaisant à n'importe quelle condition.

In [226]:
import numpy as np 
x = np.arange(9.).reshape(3, 3) 

print ('Our array is:') 
print( x ) 

# define a condition 
condition = np.mod(x,2) == 0 

print ('Element-wise value of condition' )
print( condition  )

print ('Extract elements using condition' )
print (np.extract(condition, x))

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Element-wise value of condition
[[ True False  True]
 [False  True False]
 [ True False  True]]
Extract elements using condition
[0. 2. 4. 6. 8.]


## NumPy - Bibliothèque de matrices
Le package NumPy contient une bibliothèque Matrix numpy.matlib . Ce module a des fonctions qui renvoient des matrices au lieu d'objets ndarray.

### matlib.vide()
La fonction matlib.empty() renvoie une nouvelle matrice sans initialiser les entrées. La fonction prend les paramètres suivants.

In [ ]:
numpy.matlib.empty(shape, dtype, order)

<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sr.No.</font></font></th>
<th style="text-align:center;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Paramètre et description</font></font></th>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">façonner</font></font></b></p>
<p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">int</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> ou tuple de </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">int</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> définissant la forme de la nouvelle matrice</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">TypeD</font></font></b></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Optionnel. </font><font style="vertical-align: inherit;">Type de données de la sortie</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ordre</font></font></b></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">C ou F</font></font></p>
</td>
</tr>
</tbody></table>

#### Exemple

In [ ]:
import numpy.matlib 
import numpy as np 

print (np.matlib.empty((2,2)) )
# filled with random data

### numpy.matlib.zeros() et numpy.matlib.ones()
Chacune de ces fonctions renvoie la matrice remplie respectivement de zéros ou de uns.

#### Exemple

In [ ]:
import numpy.matlib 
import numpy as np 
print (np.matlib.zeros((2,2))) 
print (np.matlib.ones((2,2)))

### numpy.matlib.eye()
Cette fonction renvoie une matrice avec 1 le long des éléments diagonaux et les zéros ailleurs. La fonction prend les paramètres suivants.

In [ ]:
numpy.matlib.eye(n, M,k, dtype)

Où,
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sr.No.</font></font></th>
<th style="text-align:center;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Paramètre et description</font></font></th>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">m</font></font></b></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Le nombre de lignes dans la matrice résultante</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">M</font></font></b></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Le nombre de colonnes, par défaut à n</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">k</font></font></b></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Indice de diagonale</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4</font></font></td>
<td><p><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">dtype</font></font></b></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Type de données de la sortie</font></font></p>
</td>
</tr>
</tbody></table>

#### Exemple

In [ ]:
import numpy.matlib 
import numpy as np 
print (np.matlib.eye(n = 3, M = 4, k = 0, dtype = float))

### numpy.matlib.identity()
La fonction numpy.matlib.identity() renvoie la matrice Identity de la taille donnée. Une matrice identité est une matrice carrée avec tous les éléments diagonaux à 1.

In [ ]:
import numpy.matlib 
import numpy as np 
print (np.matlib.identity(5, dtype = float))

### numpy.matlib.rand()
La fonction numpy.matlib.rand() renvoie une matrice de la taille donnée remplie de valeurs aléatoires.

#### Exemple

In [ ]:
import numpy.matlib 
import numpy as np 
print (np.matlib.rand(3,3))

In [ ]:
#Notez qu'une matrice est toujours à deux dimensions, alors que ndarray est un tableau à n dimensions. Les deux objets sont inter-convertibles.

import numpy.matlib 
import numpy as np  

i = np.matrix('1,2;3,4') 
print( i, '\n' )

import numpy.matlib 
import numpy as np  

j = np.asarray(i) 
print (j, '\n') 

import numpy.matlib 
import numpy as np  

k = np.asmatrix (j) 
print (k, '\n')

## NumPy - Algèbre linéaire
Le package NumPy contient le module numpy.linalg qui fournit toutes les fonctionnalités requises pour l'algèbre linéaire. Certaines des fonctions importantes de ce module sont décrites dans le tableau suivant.

<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;width:10%"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sr.No.</font></font></th>
<th style="text-align:center;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Description de la fonction</font></font></th>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1</font></font></td>
<td><a href="/numpy/numpy_dot.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">point</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Produit scalaire des deux tableaux</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2</font></font></td>
<td><a href="/numpy/numpy_vdot.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">vdot</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Produit scalaire des deux vecteurs</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3</font></font></td>
<td><a href="/numpy/numpy_inner.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">intérieur</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Produit interne des deux tableaux</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4</font></font></td>
<td><a href="/numpy/numpy_matmul.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">matmul</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Produit matriciel des deux tableaux</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5</font></font></td>
<td><a href="/numpy/numpy_determinant.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">déterminant</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Calcule le déterminant du tableau</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">6</font></font></td>
<td><a href="/numpy/numpy_solve.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">résoudre</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Résout l'équation de la matrice linéaire</font></font></p>
</td>
</tr>
<tr>
<td class="ts"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">7</font></font></td>
<td><a href="/numpy/numpy_inv.htm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">inv</font></font></a>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Trouve l'inverse multiplicatif de la matrice</font></font></p>
</td>
</tr>
</tbody></table>

## E/S avec NumPy
Les objets ndarray peuvent être enregistrés et chargés à partir des fichiers du disque. Les fonctions IO disponibles sont -

    - Les fonctions load() et save() gèrent les fichiers binaires /numPy (avec l' extension npy )

    - Les fonctions loadtxt() et savetxt() gèrent les fichiers texte normaux

NumPy introduit un format de fichier simple pour les objets ndarray. Ce fichier .npy stocke les données, la forme, le type et d'autres informations nécessaires pour reconstruire le ndarray dans un fichier disque de sorte que le tableau soit correctement récupéré même si le fichier se trouve sur une autre machine avec une architecture différente.

###  numpy.save()
Le fichier numpy.save() stocke le tableau d'entrée dans un fichier disque avec l'extension npy .

In [ ]:
import numpy as np 
a = np.array([1,2,3,4,5]) 
np.save('outfile',a)

# Pour reconstruire le tableau à partir de outfile.npy , utilisez la fonction load() .
b = np.load('outfile.npy') 
print(b)

Les fonctions save() et load() acceptent un paramètre booléen supplémentaire allow_pickles . Un pickle en Python est utilisé pour sérialiser et désérialiser des objets avant d'enregistrer ou de lire à partir d'un fichier disque.

### savetxt()
Le stockage et la récupération des données du tableau au format de fichier texte simple sont effectués avec les fonctions savetxt() et loadtxt() .

In [ ]:
# Exemple
import numpy as np 

a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt') 
print( b) 

Les fonctions savetxt() et loadtxt() acceptent des paramètres facultatifs supplémentaires tels que l'en-tête, le pied de page et le délimiteur.